createEnDict.out:CreateEnDict.cpp
	g++ testCreateEnDict.cpp CreateEnDict.cpp ../src/Mylog.cpp ../src/ReadConfigFile.cpp ../src/GetFilenameFromDir.cpp -o createEnDict.out -pthread -llog4cpp -std=c++11	
.PHONY:clean
clean:
	rm createEnDict.out
